module.exports = [
  {
    firstname: "Facundo",
    lastname: "Riñon",
    username: "Ronson",
    password: "jeje",
    email: "facundo.rinon27@gmail.com",
    avatar: "yo.jpeg",
  },
  {
    firstname: "Invited",
    lastname: "User",
    username: "Invited",
    password: "1234",
    email: "invited@gmail.com",
    avatar: "nullAvatar.png",
  },
  {
    firstname: "SAMAN",
    lastname: "Master",
    username: "Saman",
    password: "1234",
    email: "saman@gmail.com",
    avatar: "saman.jpg",
  },
  {
    firstname: "Burguer",
    lastname: "Knight",
    username: "BKnight",
    password: "1234",
    email: "BKnight@gmail.com",
    avatar: "burguer.jpeg",
  },
  {
    firstname: "Salad",
    lastname: "God",
    username: "SaladKinga",
    password: "1234",
    email: "SaladKinga@gmail.com",
    avatar: "salad.jpg",
  },
  {
    firstname: "BBeef",
    lastname: "King",
    username: "BBKing",
    password: "1234",
    email: "BBKing@gmail.com",
    avatar: "beef.jpg",
  },
  {
    firstname: "Fishi",
    lastname: "&Rise",
    username: "Fishi&Rise",
    password: "1234",
    email: "F&R@gmail.com",
    avatar: "sushi.jpg",
  },
  {
    firstname: "Brave",
    lastname: "Chicken",
    username: "BraveChkn",
    password: "1234",
    email: "BChkn@gmail.com",
    avatar: "chicken.jpg",
  },
  {
    firstname: "Pizzaronni",
    lastname: "!",
    username: "Pizzaronni",
    password: "1234",
    email: "Pizzaronni@gmail.com",
    avatar: "pizza.jpeg",
  },
];
